//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health_Care_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratoryResult
    {
        public int id { get; set; }
        public Nullable<int> testId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Results { get; set; }
        public string Notes { get; set; }
    
        public virtual laboratory laboratory { get; set; }
    }
}
