//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health_Care_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public int id { get; set; }
        public Nullable<int> conultation { get; set; }
        public Nullable<int> patient { get; set; }
        public Nullable<int> staff { get; set; }
        public Nullable<int> medication { get; set; }
        public string Dosage { get; set; }
        public string frequency { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Medication Medication1 { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
