//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health_Care_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public laboratory()
        {
            this.laboratoryResults = new HashSet<laboratoryResult>();
        }
    
        public int testId { get; set; }
        public Nullable<int> patient { get; set; }
        public Nullable<int> staff { get; set; }
        public string testType { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Staff Staff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laboratoryResult> laboratoryResults { get; set; }
    }
}
